project:
  type: website

website:
  title: "ISSS626 Coursework"
  navbar:
    left: 
    - text: "Hands-on Exercise"
      menu:
      - text: "Week1_Hands-on Exercise 1"
        href: Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html
      - text: "Week1_Hands-on Exercise 1a"
        href: Hands-on_Ex/Hands-on_Ex01a/Hands-on_Ex01a.html
      - text: "Week2_Hands-on Exercise 2"
        href: Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html
      - text: "Week2_Hands-on Exercise 2a"
        href: Hands-on_Ex/Hands-on_Ex02a/Hands-on_Ex02a.html
      - text: "Week3_Hands-on Exercise 3"
        href: Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html
      - text: "Week4_Hands-on Exercise 4"
        href: Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html
      - text: "Week5_Hands-on Exercise 5"
        href: Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05.html
      - text: "Week5_Hands-on Exercise 5a"
        href: Hands-on_Ex/Hands-on_Ex05a/Hands-on_Ex05a.html
      - text: "Week6_Hands-on Exercise 6"
        href: Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.html
 
    - text: "In-class Exercise"
      menu:
      - text: "In-class Exercise 3a"
        href: In-class_Ex/In-class_Ex03a/In-class_Ex03a.html
      - text: "In-class Exercise 3b"
        href: In-class_Ex/In-class_Ex03b/In-class_Ex03b.html
      - text: "In-class Exercise 4"
        href: In-class_Ex/In-class_Ex04/In-class_Ex04.html
      - text: "In-class Exercise 5"
        href: In-class_Ex/In-class_Ex05/In-class_Ex05.html
        
    - text: "Take-home Exercise"
      menu:
      - text: "Take-home Exercise 1"
        href: Take-home_Ex01/Take-home_Ex01.html

     
    
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

