---
title: "In-class Exercise 6"
author: "Jeounghyun Kim"
date: "September 25, 2025"
date-modified: "last-modified" 
execute:
  echo: true
  eval: true
  warning: false
  freeze: false
---

```{r}
pacman::p_load(sf, rgeoda, tidyverse,tmap)
```

**Bus Stop Location**

```{r}
BusStop = st_read(dsn="data/LTADataMall/",
                  layer="BusStop") %>%
  st_transform(crs =3414)
```

**Master Plan 2019 Subzone**

```{r}
mpsz <- read_rds("data/rds/mpsz_sf.rds")
```

**O-D Bus Trips**

```{r}
odbus <- read_csv("data/LTADataMall/origin_destination_bus_202508.csv")
```

```{r}
tm_shape(mpsz) + tm_polygons() + tm_shape(BusStop) +tm_dots()
```

**Extracting Bus Stops within Singapore**

```{r}
BusStop_in_SG <- st_join(
  BusStop, mpsz,
  join = st_within,
  left = FALSE
)
```

```{r}
tm_shape(mpsz) + tm_polygons() + tm_shape(BusStop_in_SG) +tm_dots()
```

Checking the generated hexagons reveals that it covers all the bus stops

**Deriving Analytical Hexagon**

```{r}
#The grid size here is 700 meters. Make sure to decide which meter value you want to use for your take-home exercise

hexagon <- st_make_grid(mpsz, cellsize =700, what = "polygon", square=FALSE) %>%
  st_sf() # no unique id for now
```

**Filtering hexagons with bus stops**

```{r}
hexagon$n_collisions = 
  lengths(st_intersects(
    hexagon, BusStop_in_SG
  ))

hexagon <- filter(hexagon, n_collisions >0)
```

**Assigining ids to each hexagon**

```{r}
library(knitr)

hexagon <- hexagon %>%
  select(, -n_collisions)

hexagon$HEX_ID <- sprintf(
  "H%04d", seq_len(nrow(hexagon))) %>%
    as.factor()

kable(head(hexagon))
```

**Preparing Trip Generation Data**

**Cleaning the data**

```{r}
trips <- odbus %>%
  select(ORIGIN_PT_CODE, DAY_TYPE, TIME_PER_HOUR, TOTAL_TRIPS) %>%
  rename(
    BUS_STOP_N = ORIGIN_PT_CODE,
    HOUR_OF_DAY = TIME_PER_HOUR,
    TRIPS = TOTAL_TRIPS
  )
trips$BUS_STOP_N <- as.factor(trips$BUS_STOP_N) #bus code -> change it to factor
kable(head(trips))
```

```{r}
bs_hex <- st_intersection(
  BusStop, hexagon
) %>%
  st_drop_geometry() %>%
  select(BUS_STOP_N, HEX_ID)

kable(head(bs_hex))

```

**Adding HEX_ID into bus trips data**

```{r}
#| eval: false
#| message: false
#| warning: false
#| include: false
#trips <- inner_join(trips, bs_hex)
#kable(head(trips)
```
