---
title: "Hands-on Exercise 1"
author: "Jeounghyun Kim"
date-modified: "last-modified" 
execute:
  echo: true
  eval: true
  warning: false
  freeze: true
---

# **1  Geospatial Data Science with R**

## **1.1 Learning Outcome**

By completing this hands-on exercise, you will learn how to:

-   Install and load **sf** and **tidyverse** packages in R.

-   Import **geospatial data** using `sf` functions.

-   Import **aspatial data** using `readr`.

-   Explore simple feature data frames with **Base R** and **sf** functions.

-   Assign or transform **coordinate systems** using `sf`.

-   Convert aspatial data into an **sf data frame**.

-   Perform **geoprocessing** with `sf`.

-   Perform **data wrangling** with `dplyr`.

-   Conduct **Exploratory Data Analysis (EDA)** with `ggplot2`.

## **1.2 Data Acquisition**

Data are key to data analytics including geospatial analytics. Hence, before analysing, we need to assemble the necessary data. In this hands-on exercise, you are required to extract the necessary data sets from the following sources:

-   Master Plan 2014 Subzone Boundary (Web) from [data.gov.sg](https://data.gov.sg/)

-   Pre-Schools Location from [data.gov.sg](https://data.gov.sg/)

-   Cycling Path from [LTADataMall](https://www.mytransport.sg/content/mytransport/home/dataMall.html)

-   Latest version of Singapore Airbnb listing data from [Inside Airbnb](http://insideairbnb.com/get-the-data.html)

### **1.2.1 Extracting the geospatial data sets**

To get started, create a new folder called *Hands-on_Ex* in a working directory.

Next, create a new sub-folder called *Hands-on_ex01* in the newly created *Hands-on_Ex* folder.

In the `Hands-on_Ex01` folder, create a sub-folder called `data`. Then, inside the `data` sub-folder, create two sub-folders and name them `geospatial` and `aspatial` respectively.

Place `Master Plan 2014 Subzone Boundary (Web)`, `Pre-Schools Location` and `Cycling Path`zipped files into `geospatial` sub-folder and unzipped them. Copy the unzipped files from their respective sub-folders and place them inside `geospatial` sub-folder.

## **1.3 Getting Started**

In this hands-on exercise, two R packages will be used. They are:

-   **sf** for importing, managing, and processing geospatial data, and

-   **tidyverse** for performing data science tasks such as importing, wrangling and visualising data.

::: callout-note
Tidyverse consists of a family of R packages. In this hands-on exercise, the following packages will be used:

-   **readr** for importing csv data,

-   **tidyr** for manipulating data,

-   **dplyr** for transforming data, and

-   **ggplot2** for visualising data
:::

Load the necessary R packages

```{r}
pacman::p_load(sf, tidyverse)
```

## **1.4 Importing Geospatial Data**

In this section, you will learn how to import the following geospatial data into R by using [*st_read()*](https://r-spatial.github.io/sf/reference/st_read.html) of **sf**package:

-   `MP14_SUBZONE_WEB_PL`, a polygon feature layer in ESRI shapefile format,

-   `CyclingPath`, a line feature layer in ESRI shapefile format, and

-   `PreSchool`, a point feature layer in kml file format.

### **1.4.1 Importing polygon feature data in shapefile format**

-   Use **`st_read()`** from **sf** package to import shapefiles.

-   Required arguments:

    -   **`dsn`** → data path

    -   **`layer`** → shapefile name (without `.shp`, `.dbf`, `.prj`, `.shx`).

-   Output: polygon feature data frame.
